Vagrant.configure(2) do |config|

  config.vm.box = "<%= image %>"

  <% if(image_url != ''){ %>
  config.vm.box_url = "<%= image_url %>"
  <% } %>

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 2
  end

  <% for(var i=0; i<volumes.length; i++) {%>
  config.vm.synced_folder "<%= volumes[i][0] %>", "<%= volumes[i][1] %>", type: "nfs"
  <% } %>

  config.vm.network "private_network", type: "dhcp"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end
end
